repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending   # includes an autofix
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
    -   id: ruff_lint
        name: lint
        entry: uv run ruff check
        args: ["--fix", "--exit-non-zero-on-fix"]
        language: system
        types: [python]
    -   id: ruff_format
        name: format
        entry: uv run ruff format
        args: ["--check"]
        language: system
        types: [python]
